name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8633643964d718f44b7a25eb20418dc42fcf9bc6bd27564f03a6e5e262f2b791"

[versions]
fabric = "0.19.1"
minecraft = "26.1"

[options]
acceptable-game-versions = ["26.1-pre-1", "26.1-rc-2"]
