name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70255aad92740a84f568fcc5429ba3ce9ddcd22322322eb8a6ae917cffbafba4"

[versions]
fabric = "0.19.1"
minecraft = "1.19.4"
