name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e393c145266e8552fe9fca89481d7d933b7c4646a2b008756cd3abca069afea4"

[versions]
fabric = "0.19.1"
minecraft = "1.20.6"
