name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b999012e3862fef52802db06ea725b46ea12920599e6764d5bf422dcad21819"

[versions]
fabric = "0.19.1"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1"]
