name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cdc78b1edae3cee4d6b609c32bc980ecf4c8fe5d9f1b3183af680492db2380a"

[versions]
fabric = "0.19.1"
minecraft = "1.21"
