name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3f10a7fe1560201e5fed73965ba282c44b0f739a264f718d7ca657532d7063a"

[versions]
fabric = "0.19.1"
minecraft = "1.21"
