name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "659dcf198fe74fdfebec80d184a26948fa46bdec8e8c53a0207bad3b4e3fa398"

[versions]
fabric = "0.19.1"
minecraft = "1.21"
