name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c7f433a7427ed8ab1af513c7b94dcf5e9ec01feba365250c2e799d76e28478d"

[versions]
fabric = "0.19.1"
minecraft = "26.1"

[options]
acceptable-game-versions = ["26.1-pre-1", "26.1-rc-2"]
