name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f801dd53a37e0e65a0f6f5a670554ca2c5af8a5a39556a02a60249b1c758160a"

[versions]
fabric = "0.19.1"
minecraft = "1.17.1"
