name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3c7684513948562e3ceaba6b6cd3fb2513437a40901d71c9d45c4ec8b75ee1f"

[versions]
fabric = "0.19.1"
minecraft = "1.17.1"
