name = "RedstoneToolkit"
author = "Scorpio"
version = "0.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1494ed0ed0f73b4f668677f1adbbbbd45dda376de4996aeef28bb0ec3c4bfca"

[versions]
fabric = "0.19.1"
minecraft = "1.20.6"
