name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee7eb5a49cb4879399d67f4be0b722641ed393b09177f18eecadd39d6338a688"

[versions]
fabric = "0.19.1"
minecraft = "1.20.6"
