name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "303c62e03f57dd9780dea952a4773285ba9dce7374893027949f02e6e1884f2c"

[versions]
fabric = "0.19.1"
minecraft = "26.2-snapshot-3"

[options]
acceptable-game-versions = ["26.2-snapshot-1", "26.2-snapshot-2"]
