name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32c315fadeeb363bb87f4baa1a86590eff2debce4525a3e402e6b28384dfa5c6"

[versions]
fabric = "0.19.1"
minecraft = "1.16.5"
