name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0b052202dac10dee0dbf76eadb4efc6f6df92e54c59cbe5e9f4b047d54fbaac"

[versions]
fabric = "0.19.1"
minecraft = "1.16.5"
