name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e37dd74f51613127e5c0ad677fa0ce53256fa72fb8e269ca99f7e054ab5d4954"

[versions]
fabric = "0.19.1"
minecraft = "1.17.1"
