name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34c16ffd0584cf11595faa46b5cda9259994b11bf44ccf4dadc12e791664ff90"

[versions]
fabric = "0.19.1"
minecraft = "1.19.4"
