name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12704070abb580eda2a8694ab3a1576fce227feedf839e5e4a35d24d5e07b3aa"

[versions]
fabric = "0.19.1"
minecraft = "1.19.4"
