name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a83834d35bd7144d6e4d5cb0283b3122acfdd6e17ca107e3f3272588f1821dc"

[versions]
fabric = "0.19.1"
minecraft = "1.18.2"
