name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e469cdaf8a2c2336eaf8740f90b6c8063085f086b8f546d62868b0b07d94928"

[versions]
fabric = "0.19.1"
minecraft = "1.18.2"
