name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13853a4af665b940e7ad61be5c082917e49608846c1857a0389cfdaf04082946"

[versions]
fabric = "0.19.1"
minecraft = "1.18.2"
