name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c297b2bc601288cfce945372802ca97b2235a55aa21ba440c2279df2fc15bce"

[versions]
fabric = "0.19.1"
minecraft = "1.18.2"
