name = "RedstoneToolkit"
author = "Scorpio"
version = "0.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26cc61544f36f5b8316790e72ee3153780afe264c9435b5d19619f535ff64c4a"

[versions]
fabric = "0.19.1"
minecraft = "1.18.2"
