name = "RedstoneToolkit"
author = "Scorpio"
version = "0.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e22a5612baafbcd33194b72ab673c2bc4878209381431fd63f9c2c2c1da9990"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
