name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1221ee91f24ed91242455da4e2d6f688422eac46c124d2403d69353b908057ce"

[versions]
fabric = "0.19.1"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
