name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86ace29a84a3d71a154d1688a02b22980e812a4d08ce9010a9ad1d8dc205f7f5"

[versions]
fabric = "0.19.1"
minecraft = "1.21"
