name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "079f0c081acd917bd7552a89ca7713ca70174fa592ae69f8d759ef9a290b465b"

[versions]
fabric = "0.19.1"
minecraft = "1.21"
