name = "RedstoneToolkit"
author = "Scorpio"
version = "0.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d9824fd92d098794a925c26ba8c2783910e3b6a46c8e6fabbda247d1fd21fe4"

[versions]
fabric = "0.19.3"
minecraft = "1.21"
