name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58059e85f8b77b179aead59506c4f4694edd59e978b38840ba1f17bb4b606e23"

[versions]
fabric = "0.19.1"
minecraft = "1.21.11"
