name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "887531ea91ba6c20fc957b8c2051a75dafb956046ac6c3eb652842f42a5595c8"

[versions]
fabric = "0.19.1"
minecraft = "1.21.11"
