name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3086b092a54e5dd985f351ff92a9d6d2cbe9421e8b17d685ad12eb0bbb467ac2"

[versions]
fabric = "0.19.1"
minecraft = "1.21.11"
