name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "daabdd2d623dc141a500382fc4a7216d3b2c85b3c819646192fb995f0ffd0f7d"

[versions]
fabric = "0.19.1"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1"]
