name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88f2e35645100e9a2031f8085c2868e00340ffcdb6da3108c421baaaca0ca776"

[versions]
fabric = "0.19.1"
minecraft = "1.16.5"
