name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eab255e54bdc4089fc426552896d5fe48af96436aad9f1da9c84cde68a9de7e3"

[versions]
fabric = "0.19.1"
minecraft = "1.16.5"
