name = "RedstoneToolkit"
author = "Scorpio"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c6e6471d16f35d66c3777b8b94f449009ad8dc89c598a1cb58ac45b3632caab"

[versions]
fabric = "0.19.1"
minecraft = "1.16.5"
